Load polyfills only if browser is IE
CityOfNewYork/ACCESS-NYC pull request #270
Opened 2020-10-26 18:20 UTC by theasteve

2020-10-26 18:34 UTC, devowhippit requested changes
@theasteve looks like a good approach. Does this account for the polyfills in the other scripts? "archive-location.js", "archive-programs.js", "screener.js", single-location.js", "single-programs.js" ?

2020-10-26 18:34 UTC, devowhippit commented on wp-content/themes/access/src/js/main.js
> +import Utility from 'modules/utility';
This module shouldn't be loaded into main.js

2020-10-27 14:49 UTC, theasteve commented
> @theasteve looks like a good approach. Does this account for the polyfills in the other scripts? "archive-location.js", "archive-programs.js", "screener.js", single-location.js", "single-programs.js" ?

@devowhippit it seems to work for most of the polyfills in those files, althought I notice an error in IE 
<img width="1121" alt="Screen Shot 2020-10-26 at 1 16 26 PM" src="https://user-images.githubusercontent.com/14843767/97318068-db880f00-1841-11eb-8b21-251f0fede3ac.png"> coming from the screener.js file. I wonder if this is an issue coming from this implementation.

2020-10-27 15:01 UTC, devowhippit requested changes
@theasteve You need to make sure that all of the other scripts polyfills are included in the new file you are creating. A bug in IE indicates that this is not ready for review. Please included the polyfills that exist in all of the other files I mentioned and make sure that IE is clear of errors in the console before assigning back to me. DM with any questions regarding this.

2020-10-27 21:13 UTC, theasteve commented
> @theasteve You need to make sure that all of the other scripts polyfills are included in the new file you are creating. A bug in IE indicates that this is not ready for review. Please include the polyfills that exist in all of the other files I mentioned in the new polyfill script you are creating and make sure that IE is clear of errors in the console before assigning back to me. DM with any questions regarding this.

<img width="1160" alt="Screen Shot 2020-10-27 at 4 55 01 PM" src="https://user-images.githubusercontent.com/14843767/97362608-a7c7dc00-1877-11eb-822e-3189faf7ecfd.png">
<img width="1149" alt="Screen Shot 2020-10-27 at 5 00 39 PM" src="https://user-images.githubusercontent.com/14843767/97362651-b44c3480-1877-11eb-9db4-14e263cc2075.png">
No errors are being displayed in new implemetation of Polyfills

2020-10-28 13:39 UTC, devowhippit requested changes
Getting close! **main.js** is not the only script that uses polyfills. You've enqueued the script there but their module deps will need to be moved into the new script.

* **A)** Remove polyfills from other view scripts and **B)** move them into the main **polyfill.js**. Do **(B)** only _if_ they are not imported into **polyfill.js** already.
* Make the IE conditional DRY. Add function `is_ie() { ...` to **lib/functions.php** and call that method when enqueueing the script `if (is_ie()) { ...`

DM me with any Qs.

2020-10-28 16:37 UTC, theasteve commented
> Getting close! **main.js** is not the only script that uses polyfills. You've enqueued the script there but their module deps will need to be moved into the new script.
> 
>     * **A)** Remove polyfills from other view scripts and **B)** move them into the main **polyfill.js**. Do **(B)** only _if_ they are not imported into **polyfill.js** already.
> 
>     * Make the IE conditional DRY. Add function `is_ie() { ...` to **lib/functions.php** and call that method when enqueueing the script `if (is_ie()) { ...`
> 
> 
> DM me with any Qs.

@devowhippit I tested the pages on IE, no errors are being logged into the console. I check the `polyfill.js` for duplicates

2020-10-28 17:48 UTC, devowhippit approved these changes
@theasteve Awesome, great work!

2020-10-28 18:11 UTC, merged